version: "3.9"
services:
  service_a:
    build:
      dockerfile: Dockerfile
      context: ./service-a
    ports:
      - "3000:3000"
  service_b:
    build:
      dockerfile: Dockerfile
      context: ./service-b
    ports:
      - "3001:3001"
  registry:
    build:
      dockerfile: Dockerfile
      context: ./registry
    ports:
      - "4000:4000"