version: "3.8"

services:
  db:
    container_name: db
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: disclone
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - disclone_network
    ports:
      - 5432:5432

volumes:
  db:

networks:
  disclone_network:
    name: disclone_network
