version: "3.8"
services:
  server:
    container_name: server
    build:
      context: .
    volumes:
      - .:/disclone:rw,delegated
    networks:
      - disclone_network
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    ports:
      - 8000:8000
      - 2345:2345

networks:
  disclone_network:
    name: disclone_network
